permissions:
  id-token: write

on:
  workflow_dispatch:
    push:
      branches: [ master ]
jobs:
  deploy:
    run-on: ubuntu-latest
    steps:
      name: Checkout
      uses: actions/checkout@v3

